version: "3"
services:
    x4_s4one-pgdb:
        image: registry.kkops.cc/x4-pg:v2
        ports:
            - "5432:5432"
    x4_s4one:
        image: registry.kkops.cc/x4-s4one:${TAG}
        ports:
            - "3000:3000"
        environment:
            - DB_HOST=${HOST_IP}
            - DB_NAME=X4DB
        volumes:
            - /var/log/x4_s4one:/var/log/x4_s4one
        restart: on-failure
        healthcheck:
          test: ["CMD-SHELL", "netstat -tnlp | grep 3000"]
          interval: 10s
          timeout: 10s
          retries: 5
        depends_on:
            -  x4_s4one-pgdb

